name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: yarn install
      - name: Run build task
        run: yarn build
      # You can customize the remote directory as per your server setup
      - name: Deploy to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          path: dist/
          switches: -avzr --delete --exclude=.env
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
